Fixed crash in DeskClock during monkey test.
Getting below crash when running monkey test
java.lang.NullPointerException: Parameter specified as non-null is null
method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter
event at com.android.deskclock.LabelDialogFragment$ImeDoneListener
.onEditorAction(Unknown Source:7)

event parameter is currently declared as non null. it can be null also,
So declaring it as null parameter.

Test: start monkey test run using below command
adb shell monkey -v 10000000

Change-Id: I2f9240d596e5011c57653d9cd04bdb8bce334c63
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>